version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - rebo_static_volume:/rebo/static
      - rebo_file_volume:/rebo/media
    networks:
      - nginx_network


volumes:
  rebo_static_volume:
    external: true
  rebo_file_volume:
    external: true
networks:
  nginx_network:
    external: true