# Generated by Django 3.2 on 2024-01-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/8992f5f5-b3db-4bbd-8f74-0a5099b0a8c2/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_time_online',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
