# Generated by Django 4.2 on 2024-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/8cb8bc71-2bc3-4361-a3ea-1fb5ddaefc61/'),
        ),
    ]
