# Generated by Django 3.2 on 2024-01-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20240109_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/311e38a5-5482-43e3-a6ee-f520991fdeee/'),
        ),
    ]
