# Generated by Django 4.2 on 2024-01-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/b5ccbd3b-60f0-4e28-b2ab-6ee02e6342d4/'),
        ),
    ]
