# Generated by Django 4.2 on 2024-01-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/361e2e88-d2d6-4325-bc43-3dcd12472273/'),
        ),
    ]
