# Generated by Django 4.2 on 2024-01-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/df66668e-544d-48bb-9f03-a9817ab3d96a/'),
        ),
    ]
