# Generated by Django 4.2 on 2024-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_related_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room_name',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
    ]
