# Generated by Django 3.2 on 2023-01-06 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_userbalance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertransaction',
            name='received_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_transaction', to='transaction.transaction'),
        ),
        migrations.AlterField(
            model_name='transfertransaction',
            name='sender_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender_transaction', to='transaction.transaction'),
        ),
    ]
