# Generated by Django 4.1.3 on 2022-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_options_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'charge'), (2, 'purchase'), (3, 'receiver'), (4, 'transfer')], default=1),
        ),
    ]
