# Generated by Django 4.1.3 on 2022-12-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('sender_name', models.CharField(max_length=48)),
                ('received_name', models.CharField(max_length=48)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('received_transaction', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='received_transaction', to='transaction.transaction')),
                ('sender_transaction', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='sender_transaction', to='transaction.transaction')),
            ],
        ),
    ]
