# Generated by Django 3.2 on 2023-01-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_type',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalogue.producttype'),
        ),
    ]
