# Generated by Django 3.2 on 2023-01-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_productattr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattr',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='catalogue.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalogue.productattributevalue'),
        ),
    ]
