# Generated by Django 3.2 on 2023-01-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20230111_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattr',
            name='title',
        ),
        migrations.AddField(
            model_name='productattr',
            name='attr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.productattribute'),
        ),
        migrations.AddField(
            model_name='productattr',
            name='type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.producttype'),
        ),
    ]
