# Generated by Django 3.2 on 2023-01-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattr',
            name='attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.producttype'),
        ),
    ]
