# Generated by Django 3.2 on 2023-01-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20230115_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_attribute',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='list_values',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
