# Generated by Django 3.2 on 2023-01-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20230115_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='list_attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='list_values',
        ),
    ]
