# Generated by Django 3.2 on 2022-12-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_weight_sell',
        ),
    ]
