# Generated by Django 3.2 on 2022-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_product_min_weight_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_buy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sell'), (2, 'buy')], default=1),
        ),
    ]
