# Generated by Django 3.2 on 2023-02-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20230209_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')], default=False),
        ),
    ]
