# Generated by Django 3.2 on 2023-07-07 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0012_auto_20230209_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('result', models.BooleanField(choices=[(True, 'OK'), (False, 'NO')], default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
