# Generated by Django 3.2 on 2022-12-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingHoghoogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_bime_in_day', models.IntegerField(default=0)),
                ('start_end_hoghoogh', models.CharField(max_length=32)),
                ('num_day', models.IntegerField(default=31)),
                ('darsad_all', models.IntegerField(default=0)),
                ('darsad_sarparast', models.IntegerField(default=0)),
                ('pele_one_day', models.IntegerField(default=0)),
                ('pele_one_darsad', models.IntegerField(default=0)),
                ('pele_two_day', models.IntegerField(default=0)),
                ('pele_two_darsad', models.IntegerField(default=0)),
                ('pele_three_day', models.IntegerField(default=0)),
                ('pele_three_darsad', models.IntegerField(default=0)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.location')),
            ],
            options={
                'verbose_name': 'SettingHoghoogh',
                'verbose_name_plural': 'SettingHoghooghs',
            },
        ),
        migrations.CreateModel(
            name='ListPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('price', models.IntegerField()),
                ('value_type', models.PositiveSmallIntegerField(choices=[(1, 'dates'), (2, 'etc')], default=1)),
                ('is_active', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listprice', to='company.location')),
            ],
            options={
                'verbose_name': 'ListPrice',
                'verbose_name_plural': 'ListPrices',
            },
        ),
        migrations.CreateModel(
            name='Hoghoogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_calculate', models.BigIntegerField()),
                ('sum_all', models.BigIntegerField()),
                ('days', models.IntegerField()),
                ('mosaede', models.BigIntegerField(default=0)),
                ('vam', models.BigIntegerField(default=0)),
                ('bime', models.BigIntegerField(default=0)),
                ('tashvighi', models.BigIntegerField(default=0)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('karaee', models.FloatField(default=0)),
                ('amar', models.JSONField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoghoogh', to='company.staff')),
            ],
            options={
                'verbose_name': 'Hoghoogh',
                'verbose_name_plural': 'Hoghooghs',
            },
        ),
        migrations.CreateModel(
            name='Amar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('price', models.IntegerField()),
                ('tedad', models.IntegerField()),
                ('tarikh', models.CharField(max_length=42)),
                ('listprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amarlist', to='hoghoogh.listprice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amar', to='company.staff')),
            ],
            options={
                'verbose_name': 'Amar',
                'verbose_name_plural': 'Amars',
            },
        ),
    ]
