# Generated by Django 4.1.3 on 2023-01-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoghoogh', '0002_alter_hoghoogh_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoghoogh',
            name='pele_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoghoogh',
            name='sarparasti',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoghoogh',
            name='total_pay',
            field=models.BigIntegerField(default=0),
        ),
    ]
