# Generated by Django 4.1.3 on 2023-01-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoghoogh', '0003_hoghoogh_pele_price_hoghoogh_sarparasti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sarparasti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedad_sarparastha', models.IntegerField(default=0)),
                ('sum_day_all_sarparastha', models.IntegerField(default=0)),
                ('sum_all_tolid', models.BigIntegerField(default=0)),
                ('one_price', models.BigIntegerField(default=0)),
                ('darsad', models.IntegerField(default=0)),
                ('year_month', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Sarparasti',
                'verbose_name_plural': 'Sarparastiha',
            },
        ),
    ]
