# Generated by Django 3.2 on 2023-01-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('hoghoogh', '0005_amar_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarparasti',
            name='tedad_sarparastha',
        ),
        migrations.AddField(
            model_name='sarparasti',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sarparasti',
            name='year_month',
            field=models.IntegerField(),
        ),
    ]
