# Generated by Django 3.2 on 2023-01-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoghoogh', '0006_auto_20230104_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarparasti',
            old_name='darsad',
            new_name='sum_day_sarparast',
        ),
        migrations.RenameField(
            model_name='sarparasti',
            old_name='one_price',
            new_name='sum_tolid_sarparast',
        ),
        migrations.RemoveField(
            model_name='sarparasti',
            name='sum_all_tolid',
        ),
        migrations.RemoveField(
            model_name='sarparasti',
            name='sum_day_all_sarparastha',
        ),
    ]
