# Generated by Django 3.2 on 2023-01-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoghoogh', '0007_auto_20230104_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='amar',
            name='is_sarparast',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=True),
        ),
    ]
