# Generated by Django 3.2 on 2023-01-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoghoogh', '0009_auto_20230104_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarparasti',
            name='year_month',
        ),
        migrations.AddField(
            model_name='sarparasti',
            name='month',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sarparasti',
            name='year',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
