# Generated by Django 3.2 on 2023-01-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('hoghoogh', '0011_auto_20230104_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarparasti',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sarparast', to='company.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tolid',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tolid', to='company.location'),
            preserve_default=False,
        ),
    ]
