# Generated by Django 3.2 on 2023-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoghoogh', '0012_auto_20230104_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarparasti',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
