# Generated by Django 3.2 on 2023-01-21 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_staff_codemeli'),
        ('hoghoogh', '0013_sarparasti_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoghoogh',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hoghooghs', to='company.location'),
            preserve_default=False,
        ),
    ]
