# Generated by Django 3.2 on 2023-02-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_staff_codemeli'),
        ('hoghoogh', '0014_hoghoogh_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmarArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('price', models.IntegerField()),
                ('tedad', models.IntegerField()),
                ('type', models.CharField(max_length=42)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amarlocation', to='company.location')),
            ],
            options={
                'verbose_name': 'AmarArchive',
                'verbose_name_plural': 'AmarArchives',
            },
        ),
    ]
