# Generated by Django 3.2 on 2023-02-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_staff_codemeli'),
        ('hoghoogh', '0016_amar_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoghooghArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_calculate', models.BigIntegerField()),
                ('sum_all', models.BigIntegerField()),
                ('days', models.IntegerField()),
                ('pele_price', models.BigIntegerField(default=0)),
                ('total_pay', models.BigIntegerField(default=0)),
                ('sarparasti', models.BigIntegerField(default=0)),
                ('mosaede', models.BigIntegerField(default=0)),
                ('vam', models.BigIntegerField(default=0)),
                ('bime', models.BigIntegerField(default=0)),
                ('tashvighi', models.BigIntegerField(default=0)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('karaee', models.FloatField(default=0)),
                ('amar', models.JSONField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoghoogharchives', to='company.location')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.staff')),
            ],
            options={
                'verbose_name': 'HoghooghArchive',
                'verbose_name_plural': 'HoghooghArchives',
            },
        ),
    ]
