# Generated by Django 3.2 on 2023-02-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoghoogh', '0017_hoghoogharchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amar',
            name='tedad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='amararchive',
            name='tedad',
            field=models.FloatField(),
        ),
    ]
