# Generated by Django 4.2 on 2024-01-12 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/img-category-learn/')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=48)),
                ('price', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='%Y/%m/%d/learns/')),
                ('is_active', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=False)),
                ('is_free', models.BooleanField(choices=[(True, 'رایگان'), (False, 'نقدی')], default=False)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learns', to='learn.category')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='learns', to='catalogue.producttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learn',
                'verbose_name_plural': 'Learns',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('is_active', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=False)),
                ('is_free', models.BooleanField(choices=[(True, 'رایگان'), (False, 'نقدی')], default=False)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('learn', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sections', to='learn.learn')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/img-lessons/')),
                ('video', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/video-lessons/')),
                ('three1', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/three1/')),
                ('three2', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/three2/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/voice/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=False)),
                ('is_free', models.BooleanField(choices=[(True, 'رایگان'), (False, 'نقدی')], default=False)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lessons', to='learn.section')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
