# Generated by Django 3.2 on 2023-01-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20230131_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/voice/'),
        ),
    ]
