# Generated by Django 4.2 on 2024-01-12 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('image', models.ImageField(upload_to='%Y/%m/%d/companies/')),
                ('is_active', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=False)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('family', models.CharField(max_length=48)),
                ('mobile', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='company.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('family', models.CharField(max_length=48)),
                ('mobile', models.CharField(max_length=20)),
                ('plaque', models.PositiveIntegerField()),
                ('vasat', models.CharField(max_length=10)),
                ('iran', models.PositiveSmallIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='driver', to='company.company')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('address', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='location', to='company.company')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='TypeDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'kg'), (2, 'number'), (3, 'liter')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_dates', to='company.company')),
            ],
            options={
                'verbose_name': 'TypeDate',
                'verbose_name_plural': 'TypeDates',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.PositiveSmallIntegerField(choices=[(1, 'in'), (2, 'out'), (3, 'transfer in'), (4, 'transfer out')], default=1)),
                ('value_type', models.PositiveSmallIntegerField(choices=[(1, 'kg'), (2, 'number'), (3, 'liter')], default=1)),
                ('quantity', models.BigIntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_warehouse', to='company.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='warehouse', to='company.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='driver_warehouse', to='company.driver')),
                ('typedate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='typedate_warehouse', to='company.typedates')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='TransferWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('received_transfer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='received_transfer', to='company.warehouse')),
                ('sender_transfer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='sender_transfer', to='company.warehouse')),
                ('typedate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_transfer', to='company.typedates')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
                ('family', models.CharField(max_length=48)),
                ('mobile', models.CharField(default=0, max_length=48)),
                ('codemeli', models.CharField(default=0, max_length=48)),
                ('age', models.CharField(default=0, max_length=48)),
                ('jens', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'man'), (2, 'woman')], null=True)),
                ('is_married', models.BooleanField(blank=True, choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('card_number', models.CharField(blank=True, max_length=48, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'official'), (2, 'worker'), (3, 'supervisor')], default=2)),
                ('insurance', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=False)),
                ('insurance_status', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=True)),
                ('fix_salary', models.BigIntegerField(default=0)),
                ('salon', models.PositiveSmallIntegerField(default=1)),
                ('status', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='location', to='company.location')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='balance_records', to='company.customer')),
                ('typedate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='balance_type', to='company.typedates')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
    ]
