# Generated by Django 3.2 on 2023-01-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_staff_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to='company.location'),
        ),
    ]
