# Generated by Django 4.1.3 on 2022-12-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_customer_name_alter_driver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_dates', to='company.company')),
            ],
            options={
                'verbose_name': 'TypeDate',
                'verbose_name_plural': 'TypeDates',
            },
        ),
    ]
