# Generated by Django 4.1.3 on 2022-12-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_typedates'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='typedate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='typedate_warehouse', to='company.typedates'),
            preserve_default=False,
        ),
    ]
