# Generated by Django 3.2 on 2023-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20230120_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='codemeli',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
