# Generated by Django 3.2 on 2022-12-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_transferwarehouse_typedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferwarehouse',
            name='received_name',
        ),
        migrations.RemoveField(
            model_name='transferwarehouse',
            name='sender_name',
        ),
    ]
