# Generated by Django 3.2 on 2023-01-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_staff_codemeli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.CharField(default=0, max_length=48),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(default=0, max_length=48),
        ),
    ]
