# Generated by Django 3.2 on 2022-12-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20221205_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferwarehouse',
            name='typedate',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='base_price',
        ),
    ]
