# Generated by Django 3.2 on 2023-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20230120_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='codemeli',
            field=models.CharField(default=0, max_length=48),
        ),
    ]
