# Generated by Django 3.2 on 2022-12-05 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20221205_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalance',
            name='typedate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='company.typedates'),
            preserve_default=False,
        ),
    ]
