# Generated by Django 3.2 on 2022-12-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_customerbalance_typedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='typedate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='balance_typedate', to='company.typedates'),
        ),
    ]
