# Generated by Django 3.2 on 2022-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_customerbalance_typedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbalance',
            name='typedate',
        ),
        migrations.AddField(
            model_name='customerbalance',
            name='balance_type',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
