# Generated by Django 3.2 on 2022-12-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20221205_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbalance',
            name='balance_type',
        ),
    ]
