# Generated by Django 3.2 on 2022-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_remove_customerbalance_balance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalance',
            name='typetype',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
