# Generated by Django 3.2 on 2022-12-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20221205_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbalance',
            name='typedate',
        ),
    ]
