# Generated by Django 3.2 on 2022-12-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_transferwarehouse_typedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedates',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'kg'), (2, 'number'), (3, 'liter')], default=1),
        ),
    ]
