# Generated by Django 3.2 on 2022-12-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_typedates_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default=1, upload_to='companies/'),
            preserve_default=False,
        ),
    ]
