# Generated by Django 3.2 on 2022-12-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_alter_company_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
    ]
