# Generated by Django 3.2 on 2022-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'inactive')], default=2),
        ),
    ]
