# Generated by Django 3.2 on 2022-12-12 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('family', models.CharField(max_length=32)),
                ('mobile', models.PositiveIntegerField(max_length=20)),
                ('image', models.ImageField(upload_to='users/')),
                ('shaba', models.PositiveIntegerField(max_length=24)),
                ('image_shaba', models.ImageField(upload_to='shabas/')),
                ('codemeli', models.PositiveIntegerField(max_length=24)),
                ('image_codemeli', models.ImageField(upload_to='codemelis/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
