# Generated by Django 3.2 on 2022-12-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='codemeli',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='info',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='shaba',
            field=models.CharField(max_length=24),
        ),
    ]
