# Generated by Django 3.2 on 2024-01-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='shaba',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
