# Generated by Django 3.2 on 2023-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/users/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image_codemeli',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/codemelis/'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image_shaba',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/shabas/'),
        ),
    ]
