# Generated by Django 3.2 on 2022-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20221212_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='is_active',
            field=models.BooleanField(choices=[(1, 'active'), (2, 'inactive')], default=2),
        ),
    ]
