# Generated by Django 4.2 on 2024-01-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_servicetype_storage_service_farmer_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='family',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
    ]
