# Generated by Django 4.2 on 2024-01-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_info_family_remove_info_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='unm',
            new_name='num',
        ),
    ]
