# Generated by Django 4.2 on 2024-01-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_rename_unm_service_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'ServiceType', 'verbose_name_plural': 'ServiceTypes'},
        ),
    ]
