# Generated by Django 3.2 on 2023-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20230708_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='codemeli',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='family',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='shaba',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
