# Generated by Django 3.2 on 2023-01-11 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230111_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('c00085a5-53c3-4238-8029-b9cd4537b947'), unique=True),
        ),
    ]
