# Generated by Django 3.2 on 2023-01-11 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('5078bc8f-29f9-4a77-89c8-477b55a52360'), unique=True),
        ),
    ]
