# Generated by Django 3.2 on 2023-01-14 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('6d34f6e3-014c-4e5e-9f9f-992fa0db36dd'), unique=True),
        ),
    ]
