# Generated by Django 3.2 on 2023-01-14 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('36971ef1-bc67-4eb7-9113-e7d3bb2e8778'), unique=True),
        ),
    ]
