# Generated by Django 3.2 on 2023-01-15 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('b93b6983-084e-48bb-a899-340b6faf7932'), unique=True),
        ),
    ]
