# Generated by Django 3.2 on 2023-01-16 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('f1af7186-c0aa-4741-b6f4-bff02fd893ed'), unique=True),
        ),
    ]
