# Generated by Django 3.2 on 2023-01-17 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('b7963789-726d-483d-9d54-e5990a1d76d4'), unique=True),
        ),
    ]
