# Generated by Django 3.2 on 2023-01-19 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('ccc4c483-0268-4e29-a4e3-544dd02ee605'), unique=True),
        ),
    ]
