# Generated by Django 3.2 on 2023-01-20 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('bf4f6a6d-8d60-4ad3-a71b-46d385f52863'), unique=True),
        ),
    ]
