# Generated by Django 3.2 on 2023-01-20 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('dfcd1754-3d0b-4714-a146-a239b70e40a5'), unique=True),
        ),
    ]
