# Generated by Django 3.2 on 2023-01-20 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('0952ad2c-685f-4618-851c-882423e80638'), unique=True),
        ),
    ]
