# Generated by Django 3.2 on 2023-01-20 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('bcb82ea3-f10f-4d85-9fb3-8c370909522e'), unique=True),
        ),
    ]
