# Generated by Django 3.2 on 2023-01-21 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('d453db40-ac10-4dcc-93e2-7a3d92924f90'), unique=True),
        ),
    ]
