# Generated by Django 3.2 on 2023-01-21 01:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('a0d73773-6b83-4d91-b7f7-799691c48c3a'), unique=True),
        ),
    ]
