# Generated by Django 3.2 on 2023-01-31 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('e214071d-78b2-4539-be85-8e83358c84f9'), unique=True),
        ),
    ]
