# Generated by Django 3.2 on 2023-01-31 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('d223d0dd-878c-4081-add6-4584f2a34b34'), unique=True),
        ),
    ]
