# Generated by Django 3.2 on 2023-02-09 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('b8c6f10a-f413-4d7f-9fbd-acfd7664af41'), unique=True),
        ),
    ]
