# Generated by Django 3.2 on 2023-02-09 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('76758b04-95dd-49d2-a670-094cfbddb577'), unique=True),
        ),
    ]
