# Generated by Django 3.2 on 2023-02-20 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('8ea3d7af-9dbb-44b0-9672-4d0a928a293e'), unique=True),
        ),
    ]
