# Generated by Django 3.2 on 2023-02-20 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('5ae1cd59-effe-40f5-850b-62d327071148'), unique=True),
        ),
    ]
