# Generated by Django 3.2 on 2023-02-21 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('19e1f502-152a-4533-8f91-738d7bb8e089'), unique=True),
        ),
    ]
