# Generated by Django 3.2 on 2023-02-21 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('996ee0ca-77a9-418b-8d9f-ac5cf40e9ff3'), unique=True),
        ),
    ]
