# Generated by Django 3.2 on 2023-03-02 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('d445a085-9ce4-40e4-8825-a157b7ef9c5f'), unique=True),
        ),
    ]
