# Generated by Django 3.2 on 2023-04-17 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('b8d7d2d7-4066-47dd-8085-aadad6911c9b'), unique=True),
        ),
    ]
