# Generated by Django 3.2 on 2023-04-17 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('829488e5-e757-431c-bce0-e5868324b396'), unique=True),
        ),
    ]
