# Generated by Django 3.2 on 2023-04-17 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('b791c37f-44a4-4e8a-832d-dcc8b5e3d404'), unique=True),
        ),
    ]
