# Generated by Django 3.2 on 2023-04-17 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('f583f702-5e28-483e-9777-8417317b139f'), unique=True),
        ),
    ]
