# Generated by Django 3.2 on 2023-04-17 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('e580bc24-c311-4d0c-a470-d50e20144f14'), unique=True),
        ),
    ]
