# Generated by Django 3.2 on 2023-04-17 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('c65e7cdb-e8cb-4aa4-838a-edcaf7b49e45'), unique=True),
        ),
    ]
