# Generated by Django 3.2 on 2023-04-17 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('17fa0ca6-06a0-4f63-8fed-cacbdcbaf498'), unique=True),
        ),
    ]
