# Generated by Django 3.2 on 2023-05-06 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('7491a943-9997-4a07-afae-18aa334e0462'), unique=True),
        ),
    ]
