# Generated by Django 3.2 on 2023-05-06 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('3348f542-2f17-4874-8f89-c2a0cf2c1535'), unique=True),
        ),
    ]
