# Generated by Django 3.2 on 2023-05-06 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('6e387e64-4f45-441c-8e7a-421f354a7803'), unique=True),
        ),
    ]
