# Generated by Django 3.2 on 2023-05-06 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('da62f87b-ec90-421a-86fa-6563373da98f'), unique=True),
        ),
    ]
