# Generated by Django 3.2 on 2023-05-06 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('6845093d-906a-423e-8976-94b081c26660'), unique=True),
        ),
    ]
