# Generated by Django 3.2 on 2023-05-06 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('91ed08c9-6ea2-4550-a75c-edf9d305cae8'), unique=True),
        ),
    ]
