# Generated by Django 3.2 on 2023-05-10 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0050_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('331f69f6-e85a-4efb-8b1c-016d9d8334e1'), unique=True),
        ),
    ]
