# Generated by Django 3.2 on 2023-05-10 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0051_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('4b97055a-ecbe-4823-8407-73a820790dc5'), unique=True),
        ),
    ]
