# Generated by Django 3.2 on 2023-07-07 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('27b95286-9eee-4597-b75c-206af886c9b0'), unique=True),
        ),
    ]
