# Generated by Django 3.2 on 2023-07-07 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0053_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('30d0b7a1-dbe4-4721-b74e-5af3e371a8f3'), unique=True),
        ),
    ]
