# Generated by Django 3.2 on 2023-07-07 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('6f088232-ef04-4595-98ff-a96037288d41'), unique=True),
        ),
    ]
