# Generated by Django 3.2 on 2023-07-08 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('3f8d3127-9a2e-4f51-8d19-e9ae74b62880'), unique=True),
        ),
    ]
