# Generated by Django 3.2 on 2023-07-08 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_alter_payment_faktor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='faktor_number',
            field=models.UUIDField(default=uuid.UUID('b3831686-105e-4b40-b1b5-72742465d2ec'), unique=True),
        ),
    ]
